### ISSUE TITLE
Unlock lodash version

### ISSUE THREAD

**Issue by radeno** [thenativeweb/forcedomain#22]
Hello,

we are using your module, it is great.
But there is some small issue about dependency.

In this package is dependency (lodash) locked to specific version. Which means that there should not be used any other version.

For example after using your module it makes these dependecies:
`lodash@4.17.10, lodash@^4.0.0, lodash@^4.11.1, lodash@^4.17.10, lodash@^4.17.4, lodash@^4.17.5, lodash@^4.2.0, lodash@^4.3.0, lodash@~4.17.4`

as you can see there are multiple differenent versions required. But all begins with caret symbol (^) can increase minor version. And there is one with tilde (~) so patch version can be increased.

But your module doesn't use any characted. So only lodash version 4.17.10 is used within whole app.

Currently it is not problem because lodash latest version is 4.17.10, but in future lodash can't be updated.

**Comment by goloroden** [comment]
Thanks for your nice feedback 😊 

Regarding the pinned versions: We had problems with non-pinned versions in the past for more than one time, so we decided to always only used pinned versions, and to just update regularly, to avoid outdated packages.

The problem is just that you can't rely any more on your installs to be reproducable, and once you have a problem which is caused by this, to find and fix this error is way more annoying and time-consuming, than to update the `package.json` from time to time.

Hence, while I understand your question, we will stay with the current procedure. I hope that with this explanation this is fine for you 😊
